# 源码取自362053534/ps2sdk的bbdfa3b94ab6f0025b9d62ea3e6c73f4265448f6。
# 在BDMAssault中独立构建带共享目录前缀支持的SMBMAN。

IOP_BIN = smbman.irx

IOP_INCS += -Iinclude
IOP_LIBS += -lgcc
IOP_OBJS = smbman.o smb_fio.o smb.o poll.o auth.o des.o md4.o imports.o

include ../global.make
